#pragma once
#include "Component/Audio.h"
#include "Component/Transform.h"
#include "Component/RigidBody.h"
#include "Component/Sprite.h"
#include "Component/Collider.h"
#include "Component/LogicComponents/Text.h"
#include "Component/LogicComponents/PlayerController.h"
#include "Component/LogicComponents/Score.h"